baseURL = "https://backend.how/"
languageCode = "en-us"
title = "Everything Engineering"
theme = "coloroid"
copyright = 'backend.how © 2024 by Pratik is licensed under CC BY-SA 4.0'
enableRobotsTXT = true
enableEmoji = true

[params]
title = "Backend.how | Everything Engineering"
url = "https://backend.how/"
Description = "Pratik's blog for thoughtful articles on engineering, tech trends, and other insightful topics."
titleSeparator = "|"

# Schema.org settings
schemaType = "Person"
schemaName = "Pratik"
schemaLogo = "favicon-32x32.png"
schemaTwitter = "https://x.com/pratikgajjar_in"
schemaLinkedIn = "https://www.linkedin.com/in/pratik-gajjar"
schemaGitHub = "https://github.com/pratikgajjar"
schemaSection = "posts"
siteLinksSearchBox = true

# OpenGraph and Twitter Card settings
ogLocale = "en_US"
twitterSite = "https://x.com/pratikgajjar_in"
twitterCreator = "pratikgajjar_in"

# Images for social media sharing
images = ["/og-image.png"]

[params.author]
email = 'pg@backend.how'
name = 'Pratik'

[outputs]
home = ['html', 'amp', 'rss']
page = ['html', 'rss']

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = false
noHl = false
style = "syntax"
tabWidth = 4
[markup.goldmark]
duplicateResourceFiles = false
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
linkifyProtocol = 'https'
strikethrough = true
table = true
taskList = true
[markup.goldmark.extensions.cjk]
eastAsianLineBreaks = false
eastAsianLineBreaksStyle = 'simple'
enable = false
escapedSpace = false
[markup.goldmark.extensions.extras]
[markup.goldmark.extensions.extras.delete]
enable = true
[markup.goldmark.extensions.extras.insert]
enable = true
[markup.goldmark.extensions.extras.mark]
enable = true
[markup.goldmark.extensions.extras.subscript]
enable = true
[markup.goldmark.extensions.extras.superscript]
enable = true
[markup.goldmark.extensions.passthrough]
enable = false
[markup.goldmark.extensions.passthrough.delimiters]
block = []
inline = []
[markup.goldmark.extensions.typographer]
apostrophe = '&rsquo;'
disable = false
ellipsis = '&hellip;'
emDash = '&mdash;'
enDash = '&ndash;'
leftAngleQuote = '&laquo;'
leftDoubleQuote = '&ldquo;'
leftSingleQuote = '&lsquo;'
rightAngleQuote = '&raquo;'
rightDoubleQuote = '&rdquo;'
rightSingleQuote = '&rsquo;'
[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'
wrapStandAloneImageWithinParagraph = true
[markup.goldmark.parser.attribute]
block = false
title = true
[markup.goldmark.renderHooks]
[markup.goldmark.renderHooks.image]
enableDefault = false
[markup.goldmark.renderHooks.link]
enableDefault = false
[markup.goldmark.renderer]
hardWraps = false
unsafe = false
xhtml = false

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
disable = false
respectDoNotTrack = true
[privacy.instagram]
disable = false
simple = true
[privacy.twitter]
disable = false
enableDNT = true
simple = true
[privacy.vimeo]
disable = false
enableDNT = true
simple = true
[privacy.youtube]
disable = false
privacyEnhanced = true

[markup.tableOfContents]
endLevel = 1
ordered = true
startLevel = 0

[languages]
[languages.en.params]
reading_speed = 180


[security]
[security.funcs]
getenv = ['^HUGO_', '^CI$', '^USER$', '^HOME$', '^CF_']

[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "production"

URL = "s3:://"

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
# Cache webmanifest files for 1 week
pattern = "^.+\\.(webmanifest)$"
cacheControl = "max-age=604800, no-transform, public"
contentType = "application/manifest+json"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
